### PR TITLE
feat : Legal pages

### PR DESCRIPTION
**Pull request by Vyshnav001**

### CODE REVIEW

**Comment by anishshobithps** [comment]
image
image


Small nits and also make links hyperlink

Applicable every page

**Review by anishshobithps — DISMISSED** [review]
Final nits, just keep it Tiara instead of Tiara 2024 and only make Tiara capital where it would make sense, after that everything is good!

Merge this pr once you make those final changes

**Review by rabilrbl — CHANGES_REQUESTED** [review]
@Vyshnav001 Can we have side headings for these pages use components/shared/text 
use varient either "h1" or "h2"

**Comment by Vyshnav001** [comment]
image
is this true? @rabilrbl

**Comment by rabilrbl** [comment]
> image is this true? @rabilrbl

Looks cool

**Review by rabilrbl — APPROVED** [review]

**Pull request merged**
