### PR TITLE
Added registration button and on-spot registration events

### LINKED ISSUE #53: feat: Improve UX by adding event route component in landing page
- Remove the `Tiara Registrations out now!`
- Add the existing event route page at the end of Home page
- Add a register now button at the very bottom 

This design specially focus on mobile users as they view the landing page and navigate to event categories or register after scrolling, enhances UX.

### PR DESCRIPTION
**Pull request by joywin2003**
Fixes #53 
* Added the register now button and events component in the bottom of the landing page
* Added on-spot registration event in events page and checkout

### CODE REVIEW

**Comment by anishshobithps** [comment]
Zenflow event & Mask It is also missing on the site.

CC @joywin2003

**Comment by joywin2003** [comment]
@anishshobithps 
Mask it and zenflow is available in checkout page. for some reason it's not showing up in events page

**Comment by Vyshnav001** [comment]
> @anishshobithps Mask it and zenflow is available in checkout page. for some reason it's not showing up in events page

@joywin2003 check the events page id 5 is skipping there

**Comment by Vyshnav001** [comment]
> > @anishshobithps Mask it and zenflow is available in checkout page. for some reason it's not showing up in events page
> 
> @joywin2003 check the events page id 5 is skipping there

one event is missing in mega also so this may be the reason

**Comment by joywin2003** [comment]
Thanks Vyshnav, i found and resolved it, @anishshobithps  check it now

**Review by anishshobithps — APPROVED** [review]

**Review by rabilrbl — APPROVED** [review]
LGTM!

**Pull request merged**
