### PR TITLE
feat(navbar): Floating navbar

### LINKED ISSUE #7: floating navbar
- [X] Floating Nav (the present one is static, a floating nav would be better)

### PR DESCRIPTION
**Pull request by anishshobithps**

### CODE REVIEW

**Comment by anishshobithps** [comment]
cc @rabilrbl @joywin2003 , any changes let me know

**Comment by rabilrbl** [comment]
@anishshobithps You happy with the height? I feel it's slightly big on my 14inch

**Comment by Vyshnav001** [comment]
@anishshobithps i think it will be better if it hides when it scroll to the bottom and reveals when it scroll to the top

**Review by rabilrbl — APPROVED** [review]
LGTM

**Comment by anishshobithps** [comment]
> ill be better if it hides when it scroll to the bottom and reveals when it scroll to the top

True,  @Vyshnav001 could you make a issue for the same ? I'll see to it in the evening in a different PR.

**Pull request merged**
